-- ==============================================================================
-- SUPABASE POSTGRESQL MASTER DATA SEED
-- PERSONAL TECHNICAL DEVELOPMENT PLATFORM (AI ENGINEER & DSA TRACKS)
-- Author: JEEVANPRANAV
-- Timezone: Asia/Kolkata
-- ==============================================================================

-- 1. DSA CATEGORIES (22 Categories)
INSERT INTO dsa_categories (id, name, is_interview_critical, icon, description, order_index) VALUES
  (1, 'Arrays & Hashing', true, 'grid', 'Hash tables, frequency maps, set operations, prefix lookups', 1),
  (2, 'Prefix Sum & Matrix', false, 'table', '2D matrix traversals, prefix running sums, boundary simulation', 2),
  (3, 'Two Pointers', true, 'git-commit', 'Left-right pointers, fast-slow pointers, sorted array manipulation', 3),
  (4, 'Sliding Window', true, 'move-horizontal', 'Fixed and variable size windows, subarray constraints', 4),
  (5, 'Stack & Monotonic Stack', true, 'layers', 'Next greater element, expression evaluation, histogram area', 5),
  (6, 'Binary Search', true, 'search', 'Search on answer space, lower/upper bounds, rotated arrays', 6),
  (7, 'Linked List', false, 'link', 'Pointer manipulation, cycle detection, reordering, reversal', 7),
  (8, 'Strings & Pattern Matching', false, 'type', 'String transformations, palindrome checks, anagrams', 8),
  (9, 'Binary Trees', true, 'git-branch', 'DFS/BFS traversals, LCA, tree construction, path sums', 9),
  (10, 'Binary Search Trees', false, 'git-merge', 'BST properties, inorder validation, range queries', 10),
  (11, 'Heap / Priority Queue', true, 'list-ordered', 'Top-K elements, median in stream, merge K sorted lists', 11),
  (12, 'Trie', false, 'folder-tree', 'Prefix tree, autocomplete, word search, bitwise XOR trie', 12),
  (13, 'Backtracking', true, 'corner-down-left', 'Permutations, combinations, subset generation, N-Queens', 13),
  (14, 'Graphs: BFS & DFS', true, 'network', 'Connected components, cycle detection, flood fill, bipartite graph', 14),
  (15, 'Graphs: Topological Sort, Union-Find, Shortest Path', true, 'share-2', 'Kahn algorithm, Disjoint Set Union, Dijkstra shortest path', 15),
  (16, '1D Dynamic Programming', true, 'trending-up', 'Fibonacci variants, house robber, coin change, LIS', 16),
  (17, '2D / Grid & String DP', true, 'layout-grid', 'Unique paths, edit distance, longest common subsequence', 17),
  (18, 'Knapsack, Subsequence & Interval DP', true, 'box', '0/1 Knapsack, unbounded knapsack, matrix chain multiplication', 18),
  (19, 'Greedy & Intervals', true, 'clock', 'Interval overlapping, merge intervals, activity selection', 19),
  (20, 'Bit Manipulation', false, 'binary', 'Bitwise XOR, power of two, bitmask DP, count set bits', 20),
  (21, 'Math & Number Theory', false, 'hash', 'GCD, primes sieve, modular arithmetic, fast exponentiation', 21),
  (22, 'Design (LLD-style)', true, 'cpu', 'LRU Cache, LFU Cache, Trie, Min Stack, Rate Limiter', 22)
ON CONFLICT (name) DO UPDATE SET
  is_interview_critical = EXCLUDED.is_interview_critical,
  icon = EXCLUDED.icon,
  description = EXCLUDED.description,
  order_index = EXCLUDED.order_index;

-- 2. INITIAL USER SETTINGS & FAST SYNC ROW
INSERT INTO user_sync_store (username, settings, updated_at)
VALUES ('JeevanPranav', '{"ai": {"dailyTargetMinutes": 120, "theme": "dark", "startDate": "2026-09-07"}, "dsa": {"dailyTarget": 3, "theme": "dark"}}'::jsonb, NOW())
ON CONFLICT (username) DO UPDATE SET
  updated_at = NOW();

INSERT INTO user_settings (user_id, ai_settings, dsa_settings, timezone, updated_at)
VALUES (
  'JeevanPranav',
  '{"dailyTargetMinutes":120,"learnMinutes":45,"buildMinutes":75,"reviseMinutes":5,"theme":"dark","soundEnabled":true,"startDate":"2026-09-07"}'::jsonb,
  '{"dailyTarget":3,"theme":"dark","revisionIntervals":[3,14]}'::jsonb,
  'Asia/Kolkata',
  NOW()
)
ON CONFLICT (user_id) DO UPDATE SET
  updated_at = NOW();

-- 3. DSA PROBLEMS (250 Practice Problems)
INSERT INTO dsa_problems (original_order, category_name, lc_number, problem_name, difficulty, pattern, companies, leetcode_url, priority) VALUES
  (1, 'Arrays & Hashing', 217, 'Contains Duplicate', 'Easy', 'Hash Set', 'Amazon, Microsoft, Adobe, Apple', 'https://leetcode.com/problems/contains-duplicate/', 'HIGH'),
  (2, 'Arrays & Hashing', 242, 'Valid Anagram', 'Easy', 'Frequency Map / Array', 'Amazon, Google, Bloomberg', 'https://leetcode.com/problems/valid-anagram/', 'HIGH'),
  (3, 'Arrays & Hashing', 1, 'Two Sum', 'Easy', 'Hash Map (Complement lookup)', 'Amazon, Google, Meta, Microsoft, Apple', 'https://leetcode.com/problems/two-sum/', 'HIGH'),
  (4, 'Arrays & Hashing', 49, 'Group Anagrams', 'Medium', 'Categorize by Sorted Key / Count', 'Amazon, Meta, Microsoft, Uber', 'https://leetcode.com/problems/group-anagrams/', 'HIGH'),
  (5, 'Arrays & Hashing', 347, 'Top K Frequent Elements', 'Medium', 'Bucket Sort / Min-Heap', 'Amazon, Meta, Google', 'https://leetcode.com/problems/top-k-frequent-elements/', 'HIGH'),
  (6, 'Arrays & Hashing', 238, 'Product of Array Except Self', 'Medium', 'Prefix & Suffix Products', 'Amazon, Meta, Microsoft, Apple', 'https://leetcode.com/problems/product-of-array-except-self/', 'HIGH'),
  (7, 'Arrays & Hashing', 36, 'Valid Sudoku', 'Medium', 'Bitmask / Set for Rows, Cols, Grids', 'Amazon, Apple, Uber', 'https://leetcode.com/problems/valid-sudoku/', 'HIGH'),
  (8, 'Arrays & Hashing', 128, 'Longest Consecutive Sequence', 'Medium', 'HashSet intelligent start lookup', 'Google, Amazon, Meta', 'https://leetcode.com/problems/longest-consecutive-sequence/', 'HIGH'),
  (9, 'Arrays & Hashing', 271, 'Encode and Decode Strings', 'Medium', 'Length-Prefix Delimiter', 'Google, Meta, Amazon', 'https://leetcode.com/problems/encode-and-decode-strings/', 'HIGH'),
  (10, 'Arrays & Hashing', 75, 'Sort Colors', 'Medium', 'Dutch National Flag (3 pointers)', 'Microsoft, Amazon, Meta', 'https://leetcode.com/problems/sort-colors/', 'HIGH'),
  (11, 'Arrays & Hashing', 169, 'Majority Element', 'Easy', 'Boyer-Moore Voting Algorithm', 'Amazon, Google, Microsoft', 'https://leetcode.com/problems/majority-element/', 'HIGH'),
  (12, 'Arrays & Hashing', 229, 'Majority Element II', 'Medium', 'Boyer-Moore (2 Candidates)', 'Amazon, Google', 'https://leetcode.com/problems/majority-element-ii/', 'HIGH'),
  (13, 'Arrays & Hashing', 448, 'Find All Numbers Disappeared in an Array', 'Easy', 'Index as Hash (In-place negation)', 'Amazon, Google', 'https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/', 'HIGH'),
  (14, 'Arrays & Hashing', 560, 'Subarray Sum Equals K', 'Medium', 'Prefix Sum + Hash Map', 'Meta, Google, Amazon', 'https://leetcode.com/problems/subarray-sum-equals-k/', 'HIGH'),
  (15, 'Arrays & Hashing', 380, 'Insert Delete GetRandom O(1)', 'Medium', 'Array + HashMap index lookup', 'Meta, Amazon, Google', 'https://leetcode.com/problems/insert-delete-getrandom-o1/', 'HIGH'),
  (16, 'Arrays & Hashing', 31, 'Next Permutation', 'Medium', 'Pivot and Swap Inversion', 'Google, Meta, Amazon', 'https://leetcode.com/problems/next-permutation/', 'HIGH'),
  (17, 'Arrays & Hashing', 54, 'Spiral Matrix', 'Medium', '4-Boundary Shrinking Loop', 'Microsoft, Amazon, Apple', 'https://leetcode.com/problems/spiral-matrix/', 'HIGH'),
  (18, 'Arrays & Hashing', 48, 'Rotate Image', 'Medium', 'Transpose & Reverse Matrix', 'Amazon, Microsoft, Google', 'https://leetcode.com/problems/rotate-image/', 'HIGH'),
  (19, 'Arrays & Hashing', 73, 'Set Matrix Zeroes', 'Medium', 'O(1) First Row/Col Marker', 'Microsoft, Amazon, Meta', 'https://leetcode.com/problems/set-matrix-zeroes/', 'HIGH'),
  (20, 'Arrays & Hashing', 41, 'First Missing Positive', 'Hard', 'In-place Array Bucket Sort O(n)', 'Google, Amazon, Meta', 'https://leetcode.com/problems/first-missing-positive/', 'HIGH'),
  (21, 'Two Pointers', 125, 'Valid Palindrome', 'Easy', 'Left-Right Shrinking Pointers', 'Meta, Microsoft, Amazon', 'https://leetcode.com/problems/valid-palindrome/', 'HIGH'),
  (22, 'Two Pointers', 167, 'Two Sum II - Input Array Is Sorted', 'Medium', 'Two Pointers Monotonic Search', 'Amazon, Google, Apple', 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', 'HIGH'),
  (23, 'Two Pointers', 15, '3Sum', 'Medium', 'Sort + Fixed Pivot with Two Pointers', 'Amazon, Meta, Google, Apple', 'https://leetcode.com/problems/3sum/', 'HIGH'),
  (24, 'Two Pointers', 16, '3Sum Closest', 'Medium', 'Sort + Two Pointers Minimum Delta', 'Amazon, Bloomberg, Meta', 'https://leetcode.com/problems/3sum-closest/', 'HIGH'),
  (25, 'Two Pointers', 18, '4Sum', 'Medium', 'Recursive k-Sum with Two Pointers', 'Amazon, Microsoft, Google', 'https://leetcode.com/problems/4sum/', 'HIGH'),
  (26, 'Two Pointers', 11, 'Container With Most Water', 'Medium', 'Greedy Shrinking of Shorter Line', 'Amazon, Google, Meta, Apple', 'https://leetcode.com/problems/container-with-most-water/', 'HIGH'),
  (27, 'Two Pointers', 42, 'Trapping Rain Water', 'Hard', 'Two Pointers Max Boundaries', 'Amazon, Google, Meta, Microsoft', 'https://leetcode.com/problems/trapping-rain-water/', 'HIGH'),
  (28, 'Two Pointers', 283, 'Move Zeroes', 'Easy', 'Read-Write Index Pointers', 'Meta, Apple, Amazon', 'https://leetcode.com/problems/move-zeroes/', 'HIGH'),
  (29, 'Two Pointers', 26, 'Remove Duplicates from Sorted Array', 'Easy', 'Unique Insertion Pointer', 'Microsoft, Amazon, Meta', 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/', 'HIGH'),
  (30, 'Two Pointers', 80, 'Remove Duplicates from Sorted Array II', 'Medium', 'Two-Element Window Writer', 'Amazon, Microsoft', 'https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/', 'HIGH'),
  (31, 'Two Pointers', 977, 'Squares of a Sorted Array', 'Easy', 'Opposite Ends Absolute Max', 'Amazon, Meta, Google', 'https://leetcode.com/problems/squares-of-a-sorted-array/', 'HIGH'),
  (32, 'Two Pointers', 881, 'Boats to Save People', 'Medium', 'Greedy Lightest + Heaviest Pair', 'Google, Amazon, Uber', 'https://leetcode.com/problems/boats-to-save-people/', 'HIGH'),
  (33, 'Sliding Window', 121, 'Best Time to Buy and Sell Stock', 'Easy', 'Sliding Window Min Valley Tracking', 'Amazon, Microsoft, Meta, Google', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 'HIGH'),
  (34, 'Sliding Window', 3, 'Longest Substring Without Repeating Characters', 'Medium', 'Variable Sliding Window + Last Index', 'Amazon, Google, Meta, Microsoft', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', 'HIGH'),
  (35, 'Sliding Window', 424, 'Longest Repeating Character Replacement', 'Medium', 'Max Frequency In Window Constraint', 'Amazon, Google, Uber', 'https://leetcode.com/problems/longest-repeating-character-replacement/', 'HIGH'),
  (36, 'Sliding Window', 567, 'Permutation in String', 'Medium', 'Fixed Size Frequency Match Window', 'Microsoft, Amazon, Meta', 'https://leetcode.com/problems/permutation-in-string/', 'HIGH'),
  (37, 'Sliding Window', 76, 'Minimum Window Substring', 'Hard', 'Two Pointers Shrinking Window with Character Need Map', 'Meta, Google, Amazon, Microsoft', 'https://leetcode.com/problems/minimum-window-substring/', 'HIGH'),
  (38, 'Sliding Window', 239, 'Sliding Window Maximum', 'Hard', 'Monotonic Decreasing Deque', 'Amazon, Google, Meta', 'https://leetcode.com/problems/sliding-window-maximum/', 'HIGH'),
  (39, 'Sliding Window', 209, 'Minimum Size Subarray Sum', 'Medium', 'Expanding Right & Contracting Left Window', 'Amazon, Meta, Google', 'https://leetcode.com/problems/minimum-size-subarray-sum/', 'HIGH'),
  (40, 'Sliding Window', 904, 'Fruit Into Baskets', 'Medium', 'At Most 2 Distinct Characters Window', 'Google, Amazon', 'https://leetcode.com/problems/fruit-into-baskets/', 'HIGH'),
  (41, 'Sliding Window', 1004, 'Max Consecutive Ones III', 'Medium', 'At Most K Zeroes Window', 'Meta, Google, Amazon', 'https://leetcode.com/problems/max-consecutive-ones-iii/', 'HIGH'),
  (42, 'Sliding Window', 992, 'Subarrays with K Different Integers', 'Hard', 'Exactly(K) = AtMost(K) - AtMost(K-1)', 'Amazon, Google', 'https://leetcode.com/problems/subarrays-with-k-different-integers/', 'HIGH'),
  (43, 'Sliding Window', 438, 'Find All Anagrams in a String', 'Medium', 'Sliding Window Character Counts', 'Amazon, Meta, Microsoft', 'https://leetcode.com/problems/find-all-anagrams-in-a-string/', 'HIGH'),
  (44, 'Sliding Window', 1456, 'Maximum Number of Vowels in a Substring of Given Length', 'Medium', 'Fixed Window K Rolling Sum', 'Amazon, Google', 'https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/', 'HIGH'),
  (45, 'Stack & Monotonic Stack', 20, 'Valid Parentheses', 'Easy', 'LIFO Bracket Matching', 'Amazon, Meta, Microsoft, Google', 'https://leetcode.com/problems/valid-parentheses/', 'HIGH'),
  (46, 'Stack & Monotonic Stack', 155, 'Min Stack', 'Medium', 'Two Stacks / Value-Min Pair', 'Amazon, Microsoft, Bloomberg', 'https://leetcode.com/problems/min-stack/', 'HIGH'),
  (47, 'Stack & Monotonic Stack', 150, 'Evaluate Reverse Polish Notation', 'Medium', 'Postfix Stack Evaluation', 'Amazon, Google, Meta', 'https://leetcode.com/problems/evaluate-reverse-polish-notation/', 'HIGH'),
  (48, 'Stack & Monotonic Stack', 22, 'Generate Parentheses', 'Medium', 'Backtracking / Stack Valid State', 'Amazon, Microsoft, Meta', 'https://leetcode.com/problems/generate-parentheses/', 'HIGH'),
  (49, 'Stack & Monotonic Stack', 739, 'Daily Temperatures', 'Medium', 'Monotonic Decreasing Stack', 'Amazon, Meta, Google', 'https://leetcode.com/problems/daily-temperatures/', 'HIGH'),
  (50, 'Stack & Monotonic Stack', 853, 'Car Fleet', 'Medium', 'Monotonic Stack Time to Target', 'Google, Amazon', 'https://leetcode.com/problems/car-fleet/', 'HIGH'),
  (51, 'Stack & Monotonic Stack', 84, 'Largest Rectangle in Histogram', 'Hard', 'Monotonic Increasing Stack with Width Calculation', 'Amazon, Google, Meta', 'https://leetcode.com/problems/largest-rectangle-in-histogram/', 'HIGH'),
  (52, 'Stack & Monotonic Stack', 85, 'Maximal Rectangle', 'Hard', '2D Histogram + Monotonic Stack', 'Amazon, Google, Microsoft', 'https://leetcode.com/problems/maximal-rectangle/', 'HIGH'),
  (53, 'Stack & Monotonic Stack', 901, 'Online Stock Span', 'Medium', 'Monotonic Stack with Accumulated Weights', 'Amazon, Microsoft', 'https://leetcode.com/problems/online-stock-span/', 'HIGH'),
  (54, 'Stack & Monotonic Stack', 735, 'Asteroid Collision', 'Medium', 'Stack Collision Simulation', 'Amazon, Google', 'https://leetcode.com/problems/asteroid-collision/', 'HIGH'),
  (55, 'Stack & Monotonic Stack', 456, '132 Pattern', 'Medium', 'Monotonic Decreasing Stack for Candidate Middle', 'Amazon, Google', 'https://leetcode.com/problems/132-pattern/', 'HIGH'),
  (56, 'Stack & Monotonic Stack', 402, 'Remove K Digits', 'Medium', 'Monotonic Increasing Stack Greedy Removal', 'Amazon, Microsoft', 'https://leetcode.com/problems/remove-k-digits/', 'HIGH'),
  (57, 'Stack & Monotonic Stack', 496, 'Next Greater Element I', 'Easy', 'Monotonic Stack + Hash Map', 'Amazon, Google', 'https://leetcode.com/problems/next-greater-element-i/', 'HIGH'),
  (58, 'Stack & Monotonic Stack', 503, 'Next Greater Element II', 'Medium', 'Circular Array 2x Scan with Stack', 'Amazon, Google, Meta', 'https://leetcode.com/problems/next-greater-element-ii/', 'HIGH'),
  (59, 'Binary Search', 704, 'Binary Search', 'Easy', 'Standard Lower/Upper Mid Loop', 'Amazon, Google, Microsoft, Meta', 'https://leetcode.com/problems/binary-search/', 'HIGH'),
  (60, 'Binary Search', 74, 'Search a 2D Matrix', 'Medium', 'Flattened Row/Col Binary Search', 'Amazon, Microsoft, Apple', 'https://leetcode.com/problems/search-a-2d-matrix/', 'HIGH'),
  (61, 'Binary Search', 240, 'Search a 2D Matrix II', 'Medium', 'Top-Right / Bottom-Left Pruning', 'Amazon, Microsoft, Google', 'https://leetcode.com/problems/search-a-2d-matrix-ii/', 'HIGH'),
  (62, 'Binary Search', 875, 'Koko Eating Bananas', 'Medium', 'Binary Search on Monotonic Answer Space', 'Amazon, Google, Meta', 'https://leetcode.com/problems/koko-eating-bananas/', 'HIGH'),
  (63, 'Binary Search', 153, 'Find Minimum in Rotated Sorted Array', 'Medium', 'Rotated Boundary Inflection Point', 'Amazon, Microsoft, Meta', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', 'HIGH'),
  (64, 'Binary Search', 33, 'Search in Rotated Sorted Array', 'Medium', 'Sorted Half Detection', 'Amazon, Meta, Google, Microsoft', 'https://leetcode.com/problems/search-in-rotated-sorted-array/', 'HIGH'),
  (65, 'Binary Search', 81, 'Search in Rotated Sorted Array II', 'Medium', 'Duplicates Trimming on Equal Boundaries', 'Amazon, Google', 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/', 'HIGH'),
  (66, 'Binary Search', 981, 'Time Based Key-Value Store', 'Medium', 'Binary Search on Timestamps', 'Google, Netflix, Amazon', 'https://leetcode.com/problems/time-based-key-value-store/', 'HIGH'),
  (67, 'Binary Search', 4, 'Median of Two Sorted Arrays', 'Hard', 'Binary Search on Shorter Partition', 'Google, Amazon, Meta, Microsoft', 'https://leetcode.com/problems/median-of-two-sorted-arrays/', 'HIGH'),
  (68, 'Binary Search', 162, 'Find Peak Element', 'Medium', 'Slope Follower Binary Search', 'Amazon, Meta, Google', 'https://leetcode.com/problems/find-peak-element/', 'HIGH'),
  (69, 'Binary Search', 1011, 'Capacity To Ship Packages Within D Days', 'Medium', 'Binary Search on Feasibility Predicate', 'Amazon, Google', 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/', 'HIGH'),
  (70, 'Binary Search', 410, 'Split Array Largest Sum', 'Hard', 'Binary Search on Target Range (Min of Max)', 'Google, Amazon', 'https://leetcode.com/problems/split-array-largest-sum/', 'HIGH'),
  (71, 'Binary Search', 540, 'Single Element in a Sorted Array', 'Medium', 'Index Parity (Even-Odd Pair Check)', 'Amazon, Google, Meta', 'https://leetcode.com/problems/single-element-in-a-sorted-array/', 'HIGH'),
  (72, 'Binary Search', 34, 'Find First and Last Position of Element in Sorted Array', 'Medium', 'Lower Bound & Upper Bound Binary Search', 'Meta, Google, Amazon', 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/', 'HIGH'),
  (73, 'Linked List', 206, 'Reverse Linked List', 'Easy', 'Prev-Curr-Next 3 Pointers', 'Amazon, Google, Meta, Microsoft, Apple', 'https://leetcode.com/problems/reverse-linked-list/', 'MEDIUM'),
  (74, 'Linked List', 21, 'Merge Two Sorted Lists', 'Easy', 'Dummy Head Pointer Stitching', 'Amazon, Microsoft, Meta', 'https://leetcode.com/problems/merge-two-sorted-lists/', 'MEDIUM'),
  (75, 'Linked List', 143, 'Reorder List', 'Medium', 'Find Mid + Reverse Half + Interleave', 'Meta, Amazon, Google', 'https://leetcode.com/problems/reorder-list/', 'MEDIUM'),
  (76, 'Linked List', 19, 'Remove Nth Node From End of List', 'Medium', 'Fast-Slow Fast-Forward N Steps', 'Amazon, Meta, Google', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', 'MEDIUM'),
  (77, 'Linked List', 138, 'Copy List with Random Pointer', 'Medium', 'Interweaving Nodes / HashMap Lookup', 'Amazon, Microsoft, Bloomberg', 'https://leetcode.com/problems/copy-list-with-random-pointer/', 'MEDIUM'),
  (78, 'Linked List', 2, 'Add Two Numbers', 'Medium', 'Carry-Forward Node Traversal', 'Amazon, Google, Meta, Microsoft', 'https://leetcode.com/problems/add-two-numbers/', 'MEDIUM'),
  (79, 'Linked List', 141, 'Linked List Cycle', 'Easy', 'Floyd Cycle Finding (Tortoise and Hare)', 'Amazon, Microsoft, Meta', 'https://leetcode.com/problems/linked-list-cycle/', 'MEDIUM'),
  (80, 'Linked List', 142, 'Linked List Cycle II', 'Medium', 'Floyd Cycle Entry Intersection', 'Amazon, Microsoft', 'https://leetcode.com/problems/linked-list-cycle-ii/', 'MEDIUM'),
  (81, 'Linked List', 287, 'Find the Duplicate Number', 'Medium', 'Array as Linked List Cycle Detection', 'Amazon, Google, Microsoft', 'https://leetcode.com/problems/find-duplicate-number/', 'MEDIUM'),
  (82, 'Linked List', 146, 'LRU Cache', 'Medium', 'Doubly Linked List + HashMap', 'Amazon, Meta, Google, Apple, Microsoft', 'https://leetcode.com/problems/lru-cache/', 'HIGH'),
  (83, 'Linked List', 23, 'Merge k Sorted Lists', 'Hard', 'Divide & Conquer / Min-Heap', 'Amazon, Google, Meta, Microsoft', 'https://leetcode.com/problems/merge-k-sorted-lists/', 'HIGH'),
  (84, 'Linked List', 25, 'Reverse Nodes in k-Group', 'Hard', 'Segmented K-Reverse Pointers', 'Amazon, Microsoft, Meta', 'https://leetcode.com/problems/reverse-nodes-in-k-group/', 'HIGH'),
  (85, 'Linked List', 61, 'Rotate List', 'Medium', 'Make Ring + Cut at Length - K % L', 'Amazon, Microsoft', 'https://leetcode.com/problems/rotate-list/', 'MEDIUM'),
  (86, 'Linked List', 86, 'Partition List', 'Medium', 'Two Dummy Chains (Less & Greater)', 'Amazon, Microsoft', 'https://leetcode.com/problems/partition-list/', 'MEDIUM'),
  (87, 'Binary Trees', 226, 'Invert Binary Tree', 'Easy', 'Recursive Subtree Swap', 'Google, Amazon, Meta', 'https://leetcode.com/problems/invert-binary-tree/', 'HIGH'),
  (88, 'Binary Trees', 104, 'Maximum Depth of Binary Tree', 'Easy', 'DFS Height Traversal', 'Amazon, Microsoft, Google', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', 'HIGH'),
  (89, 'Binary Trees', 543, 'Diameter of Binary Tree', 'Easy', 'Post-order Left + Right Height', 'Meta, Amazon, Google', 'https://leetcode.com/problems/diameter-of-binary-tree/', 'HIGH'),
  (90, 'Binary Trees', 110, 'Balanced Binary Tree', 'Easy', 'Bottom-Up Height Difference <= 1', 'Amazon, Google', 'https://leetcode.com/problems/balanced-binary-tree/', 'HIGH'),
  (91, 'Binary Trees', 100, 'Same Tree', 'Easy', 'Simultaneous DFS Traversal', 'Amazon, Google', 'https://leetcode.com/problems/same-tree/', 'HIGH'),
  (92, 'Binary Trees', 572, 'Subtree of Another Tree', 'Easy', 'Tree Matching DFS with IsSameTree', 'Amazon, Microsoft', 'https://leetcode.com/problems/subtree-of-another-tree/', 'HIGH'),
  (93, 'Binary Trees', 236, 'Lowest Common Ancestor of a Binary Tree', 'Medium', 'Post-order Node Bubbling', 'Meta, Amazon, Microsoft, Google', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/', 'HIGH'),
  (94, 'Binary Trees', 102, 'Binary Tree Level Order Traversal', 'Medium', 'BFS Queue with Level Size', 'Amazon, Meta, Google, Microsoft', 'https://leetcode.com/problems/binary-tree-level-order-traversal/', 'HIGH'),
  (95, 'Binary Trees', 199, 'Binary Tree Right Side View', 'Medium', 'BFS Last Element of Level / DFS Right-First', 'Meta, Amazon, Bloomberg', 'https://leetcode.com/problems/binary-tree-right-side-view/', 'HIGH'),
  (96, 'Binary Trees', 1448, 'Count Good Nodes in Binary Tree', 'Medium', 'DFS Max Along Path', 'Microsoft, Amazon', 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/', 'HIGH'),
  (97, 'Binary Trees', 105, 'Construct Binary Tree from Preorder and Inorder Traversal', 'Medium', 'Root Pivot & Map Lookups', 'Amazon, Microsoft, Meta', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', 'HIGH'),
  (98, 'Binary Trees', 124, 'Binary Tree Maximum Path Sum', 'Hard', 'Post-order Max Gain with Global Max', 'Meta, Amazon, Google', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', 'HIGH'),
  (99, 'Binary Trees', 297, 'Serialize and Deserialize Binary Tree', 'Hard', 'Pre-order Traversal with Null Tokens', 'Amazon, Meta, Microsoft', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', 'HIGH'),
  (100, 'Binary Trees', 114, 'Flatten Binary Tree to Linked List', 'Medium', 'Right-Left-Root Post-order Reversal / Morris', 'Amazon, Microsoft', 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/', 'HIGH'),
  (101, 'Binary Trees', 116, 'Populating Next Right Pointers in Each Node', 'Medium', 'Level-by-Level Pointer Linking', 'Amazon, Microsoft', 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/', 'HIGH'),
  (102, 'Binary Trees', 437, 'Path Sum III', 'Medium', 'Prefix Sum Map on DFS Paths', 'Amazon, Google', 'https://leetcode.com/problems/path-sum-iii/', 'HIGH'),
  (103, 'Binary Search Trees', 98, 'Validate Binary Search Tree', 'Medium', 'Inorder Range Constraint (Min, Max)', 'Amazon, Meta, Google, Microsoft', 'https://leetcode.com/problems/validate-binary-search-tree/', 'HIGH'),
  (104, 'Binary Search Trees', 230, 'Kth Smallest Element in a BST', 'Medium', 'Inorder Traversal Early Exit', 'Amazon, Google, Uber', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', 'HIGH'),
  (105, 'Binary Search Trees', 235, 'Lowest Common Ancestor of a Binary Search Tree', 'Medium', 'BST Value Directional Splitting', 'Amazon, Microsoft, Meta', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', 'HIGH'),
  (106, 'Binary Search Trees', 701, 'Insert into a Binary Search Tree', 'Medium', 'BST Value Insertion Search', 'Amazon, Google', 'https://leetcode.com/problems/insert-into-a-binary-search-tree/', 'MEDIUM'),
  (107, 'Binary Search Trees', 450, 'Delete Node in a BST', 'Medium', 'Inorder Successor Replacement', 'Amazon, Microsoft', 'https://leetcode.com/problems/delete-node-in-a-bst/', 'MEDIUM'),
  (108, 'Binary Search Trees', 669, 'Trim a Binary Search Tree', 'Medium', 'Recursive Low-High Boundary Pruning', 'Amazon, Bloomberg', 'https://leetcode.com/problems/trim-a-binary-search-tree/', 'MEDIUM'),
  (109, 'Binary Search Trees', 108, 'Convert Sorted Array to Binary Search Tree', 'Easy', 'Middle Element as Root Recursive Construction', 'Amazon, Meta', 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/', 'MEDIUM'),
  (110, 'Binary Search Trees', 173, 'Binary Search Tree Iterator', 'Medium', 'Stack-Simulated Inorder Traversal', 'Meta, Google, Amazon', 'https://leetcode.com/problems/binary-search-tree-iterator/', 'MEDIUM'),
  (111, 'Heap / Priority Queue', 703, 'Kth Largest Element in a Stream', 'Easy', 'Min-Heap of Size K', 'Amazon, Google', 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', 'HIGH'),
  (112, 'Heap / Priority Queue', 1046, 'Last Stone Weight', 'Easy', 'Max-Heap Simulation', 'Amazon, Apple', 'https://leetcode.com/problems/last-stone-weight/', 'HIGH'),
  (113, 'Heap / Priority Queue', 973, 'K Closest Points to Origin', 'Medium', 'Max-Heap of Size K / QuickSelect', 'Amazon, Meta, Google', 'https://leetcode.com/problems/k-closest-points-to-origin/', 'HIGH'),
  (114, 'Heap / Priority Queue', 215, 'Kth Largest Element in an Array', 'Medium', 'QuickSelect O(n) / Min-Heap', 'Meta, Amazon, Google, Apple', 'https://leetcode.com/problems/kth-largest-element-in-an-array/', 'HIGH'),
  (115, 'Heap / Priority Queue', 621, 'Task Scheduler', 'Medium', 'Max-Heap / Greedy Slot Count Formula', 'Meta, Amazon, Google', 'https://leetcode.com/problems/task-scheduler/', 'HIGH'),
  (116, 'Heap / Priority Queue', 355, 'Design Twitter', 'Medium', 'Multi-way Merge with Min-Heap', 'Amazon, Twitter, Google', 'https://leetcode.com/problems/design-twitter/', 'HIGH'),
  (117, 'Heap / Priority Queue', 295, 'Find Median from Data Stream', 'Hard', 'Two Heaps (Max-Heap Left & Min-Heap Right)', 'Google, Amazon, Meta', 'https://leetcode.com/problems/find-median-from-data-stream/', 'HIGH'),
  (118, 'Heap / Priority Queue', 767, 'Reorganize String', 'Medium', 'Max-Heap with Cooldown Buffer', 'Amazon, Google, Meta', 'https://leetcode.com/problems/reorganize-string/', 'HIGH'),
  (119, 'Heap / Priority Queue', 692, 'Top K Frequent Words', 'Medium', 'Min-Heap with Custom Frequency Comparator', 'Amazon, Uber, Google', 'https://leetcode.com/problems/top-k-frequent-words/', 'HIGH'),
  (120, 'Heap / Priority Queue', 1167, 'Minimum Cost to Connect Sticks', 'Medium', 'Min-Heap Greedy Huffman Style Merge', 'Amazon', 'https://leetcode.com/problems/minimum-cost-to-connect-sticks/', 'HIGH'),
  (121, 'Heap / Priority Queue', 502, 'IPO', 'Hard', 'Two Heaps (Capital Min-Heap & Profit Max-Heap)', 'Amazon, Google', 'https://leetcode.com/problems/ipo/', 'HIGH'),
  (122, 'Heap / Priority Queue', 373, 'Find K Pairs with Smallest Sums', 'Medium', 'Min-Heap Matrix Index Front Tracking', 'Amazon, Google', 'https://leetcode.com/problems/find-k-pairs-with-smallest-sums/', 'HIGH'),
  (123, 'Trie', 208, 'Implement Trie (Prefix Tree)', 'Medium', 'Node Array / HashMap Children Links', 'Amazon, Google, Microsoft', 'https://leetcode.com/problems/implement-trie-prefix-tree/', 'MEDIUM'),
  (124, 'Trie', 211, 'Design Add and Search Words Data Structure', 'Medium', 'Trie DFS with Wildcard Dot Matching', 'Meta, Amazon', 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', 'MEDIUM'),
  (125, 'Trie', 212, 'Word Search II', 'Hard', 'Trie + 2D Grid Backtracking', 'Amazon, Microsoft, Google', 'https://leetcode.com/problems/word-search-ii/', 'HIGH'),
  (126, 'Trie', 421, 'Maximum XOR of Two Numbers in an Array', 'Medium', 'Bitwise 0-1 Binary Trie', 'Google, Amazon', 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/', 'MEDIUM'),
  (127, 'Trie', 648, 'Replace Words', 'Medium', 'Trie Shortest Root Prefix Match', 'Amazon, Uber', 'https://leetcode.com/problems/replace-words/', 'MEDIUM'),
  (128, 'Trie', 677, 'Map Sum Pairs', 'Medium', 'Trie Prefix Value Accumulation', 'Google, Amazon', 'https://leetcode.com/problems/map-sum-pairs/', 'MEDIUM'),
  (129, 'Backtracking', 78, 'Subsets', 'Medium', 'Include / Exclude DFS Decision Tree', 'Amazon, Meta, Google', 'https://leetcode.com/problems/subsets/', 'HIGH'),
  (130, 'Backtracking', 90, 'Subsets II', 'Medium', 'Sort + Duplicate Skip on Same Level', 'Amazon, Meta', 'https://leetcode.com/problems/subsets-ii/', 'HIGH'),
  (131, 'Backtracking', 39, 'Combination Sum', 'Medium', 'Unbounded Choice DFS with Index Advancement', 'Amazon, Google, Meta', 'https://leetcode.com/problems/combination-sum/', 'HIGH'),
  (132, 'Backtracking', 40, 'Combination Sum II', 'Medium', 'Sort + Single-Use Duplicate Pruning', 'Amazon, Google', 'https://leetcode.com/problems/combination-sum-ii/', 'HIGH'),
  (133, 'Backtracking', 46, 'Permutations', 'Medium', 'Visited Bitset / Array Swap DFS', 'Amazon, Meta, Google, Microsoft', 'https://leetcode.com/problems/permutations/', 'HIGH'),
  (134, 'Backtracking', 47, 'Permutations II', 'Medium', 'Sort + Used Array Frequency Control', 'Amazon, Microsoft', 'https://leetcode.com/problems/permutations-ii/', 'HIGH'),
  (135, 'Backtracking', 79, 'Word Search', 'Medium', '2D Grid DFS In-place Character Marker', 'Amazon, Microsoft, Meta', 'https://leetcode.com/problems/word-search/', 'HIGH'),
  (136, 'Backtracking', 131, 'Palindrome Partitioning', 'Medium', 'Substring Palindrome Check + DFS Partition', 'Google, Amazon, Meta', 'https://leetcode.com/problems/palindrome-partitioning/', 'HIGH'),
  (137, 'Backtracking', 17, 'Letter Combinations of a Phone Number', 'Medium', 'Keypad Digit Mapping Recursive Expansion', 'Amazon, Microsoft, Google', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', 'HIGH'),
  (138, 'Backtracking', 51, 'N-Queens', 'Hard', 'Col / Diagonal / Anti-Diagonal Sets', 'Amazon, Google, Meta', 'https://leetcode.com/problems/n-queens/', 'HIGH'),
  (139, 'Backtracking', 37, 'Sudoku Solver', 'Hard', 'Exact Cover DFS with Grid Constraints', 'Microsoft, Amazon', 'https://leetcode.com/problems/sudoku-solver/', 'HIGH'),
  (140, 'Backtracking', 93, 'Restore IP Addresses', 'Medium', '4-Segment Valid Number DFS', 'Amazon, Google', 'https://leetcode.com/problems/restore-ip-addresses/', 'HIGH'),
  (141, 'Graphs: BFS & DFS', 200, 'Number of Islands', 'Medium', '2D Grid Flood Fill (DFS/BFS)', 'Amazon, Google, Meta, Microsoft', 'https://leetcode.com/problems/number-of-islands/', 'HIGH'),
  (142, 'Graphs: BFS & DFS', 695, 'Max Area of Island', 'Medium', 'Connected Component Area Accumulator', 'Amazon, Meta, Google', 'https://leetcode.com/problems/max-area-of-island/', 'HIGH'),
  (143, 'Graphs: BFS & DFS', 133, 'Clone Graph', 'Medium', 'Hash Map Node Mapping + BFS/DFS', 'Meta, Amazon, Google', 'https://leetcode.com/problems/clone-graph/', 'HIGH'),
  (144, 'Graphs: BFS & DFS', 417, 'Pacific Atlantic Water Flow', 'Medium', 'Reverse Reachability from Oceans', 'Amazon, Google', 'https://leetcode.com/problems/pacific-atlantic-water-flow/', 'HIGH'),
  (145, 'Graphs: BFS & DFS', 130, 'Surrounded Regions', 'Medium', 'Boundary Connected Cells Protection', 'Amazon, Google', 'https://leetcode.com/problems/surrounded-regions/', 'HIGH'),
  (146, 'Graphs: BFS & DFS', 994, 'Rotting Oranges', 'Medium', 'Multi-Source BFS Queue with Minute Ticks', 'Amazon, Microsoft, Meta', 'https://leetcode.com/problems/rotting-oranges/', 'HIGH'),
  (147, 'Graphs: BFS & DFS', 286, 'Walls and Gates', 'Medium', 'Multi-Source BFS from Gates', 'Meta, Google, Amazon', 'https://leetcode.com/problems/walls-and-gates/', 'HIGH'),
  (148, 'Graphs: BFS & DFS', 127, 'Word Ladder', 'Hard', 'Shortest Path BFS on 26-Character Transformations', 'Amazon, Google, Meta', 'https://leetcode.com/problems/word-ladder/', 'HIGH'),
  (149, 'Graphs: BFS & DFS', 207, 'Course Schedule', 'Medium', 'Cycle Detection (DFS 3-Coloring / Kahn''s)', 'Amazon, Google, Meta, Microsoft', 'https://leetcode.com/problems/course-schedule/', 'HIGH'),
  (150, 'Graphs: BFS & DFS', 210, 'Course Schedule II', 'Medium', 'Topological Sort (Kahn''s In-Degree Array)', 'Amazon, Google, Meta', 'https://leetcode.com/problems/course-schedule-ii/', 'HIGH'),
  (151, 'Graphs: BFS & DFS', 261, 'Graph Valid Tree', 'Medium', 'N-1 Edges + Connected / Union-Find', 'Google, Meta, Amazon', 'https://leetcode.com/problems/graph-valid-tree/', 'HIGH'),
  (152, 'Graphs: BFS & DFS', 323, 'Number of Connected Components in an Undirected Graph', 'Medium', 'Union-Find / Simple BFS-DFS', 'Amazon, Meta, Google', 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', 'HIGH'),
  (153, 'Graphs: BFS & DFS', 785, 'Is Graph Bipartite?', 'Medium', '2-Coloring BFS/DFS', 'Meta, Amazon, Google', 'https://leetcode.com/problems/is-graph-bipartite/', 'HIGH'),
  (154, 'Graphs: BFS & DFS', 721, 'Accounts Merge', 'Medium', 'Union-Find with Email Lookup Map', 'Meta, Amazon, Google', 'https://leetcode.com/problems/accounts-merge/', 'HIGH'),
  (155, 'Graphs: Topological Sort, Union-Find, Shortest Path', 743, 'Network Delay Time', 'Medium', 'Dijkstra Shortest Path with Min-Heap', 'Google, Amazon', 'https://leetcode.com/problems/network-delay-time/', 'HIGH'),
  (156, 'Graphs: Topological Sort, Union-Find, Shortest Path', 787, 'Cheapest Flights Within K Stops', 'Medium', 'Bellman-Ford / Modified Dijkstra', 'Amazon, Google', 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', 'HIGH'),
  (157, 'Graphs: Topological Sort, Union-Find, Shortest Path', 778, 'Swim in Rising Water', 'Hard', 'Dijkstra Min-Max / Binary Search + BFS', 'Google, Amazon', 'https://leetcode.com/problems/swim-in-rising-water/', 'HIGH'),
  (158, 'Graphs: Topological Sort, Union-Find, Shortest Path', 269, 'Alien Dictionary', 'Hard', 'Character Precedence Graph + Topological Sort', 'Meta, Google, Amazon', 'https://leetcode.com/problems/alien-dictionary/', 'HIGH'),
  (159, 'Graphs: Topological Sort, Union-Find, Shortest Path', 1584, 'Min Cost to Connect All Points', 'Medium', 'Prim''s MST / Kruskal''s with Union-Find', 'Amazon, Google', 'https://leetcode.com/problems/min-cost-to-connect-all-points/', 'HIGH'),
  (160, 'Graphs: Topological Sort, Union-Find, Shortest Path', 1631, 'Path With Minimum Effort', 'Medium', 'Dijkstra on 2D Matrix Height Effort', 'Google, Amazon', 'https://leetcode.com/problems/path-with-minimum-effort/', 'HIGH'),
  (161, 'Graphs: Topological Sort, Union-Find, Shortest Path', 547, 'Number of Provinces', 'Medium', 'Disjoint Set Union (DSU) by Rank', 'Amazon, Microsoft', 'https://leetcode.com/problems/number-of-provinces/', 'HIGH'),
  (162, 'Graphs: Topological Sort, Union-Find, Shortest Path', 684, 'Redundant Connection', 'Medium', 'Union-Find Cycle Edge Detection', 'Amazon, Google', 'https://leetcode.com/problems/redundant-connection/', 'HIGH'),
  (163, 'Graphs: Topological Sort, Union-Find, Shortest Path', 947, 'Most Stones Removed with Same Row or Column', 'Medium', 'Union-Find on Row/Col Indices', 'Google, Amazon', 'https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/', 'HIGH'),
  (164, 'Graphs: Topological Sort, Union-Find, Shortest Path', 1135, 'Connecting Cities With Minimum Cost', 'Medium', 'Kruskal''s MST with Union-Find', 'Amazon', 'https://leetcode.com/problems/connecting-cities-with-minimum-cost/', 'HIGH'),
  (165, '1D Dynamic Programming', 70, 'Climbing Stairs', 'Easy', 'Fibonacci Transition DP', 'Amazon, Google, Apple', 'https://leetcode.com/problems/climbing-stairs/', 'HIGH'),
  (166, '1D Dynamic Programming', 746, 'Min Cost Climbing Stairs', 'Easy', '1D Optimal Step Cost Recurrence', 'Amazon, Apple', 'https://leetcode.com/problems/min-cost-climbing-stairs/', 'HIGH'),
  (167, '1D Dynamic Programming', 198, 'House Robber', 'Medium', 'Skip-or-Include Max Recurrence', 'Amazon, Google, Microsoft', 'https://leetcode.com/problems/house-robber/', 'HIGH'),
  (168, '1D Dynamic Programming', 213, 'House Robber II', 'Medium', 'Circular Robber (0 to n-2 vs 1 to n-1)', 'Amazon, Microsoft', 'https://leetcode.com/problems/house-robber-ii/', 'HIGH'),
  (169, '1D Dynamic Programming', 5, 'Longest Palindromic Substring', 'Medium', 'Expand Around Center O(n^2)', 'Amazon, Microsoft, Meta, Google', 'https://leetcode.com/problems/longest-palindromic-substring/', 'HIGH'),
  (170, '1D Dynamic Programming', 647, 'Palindromic Substrings', 'Medium', 'Center Expansion Counter', 'Meta, Amazon, Google', 'https://leetcode.com/problems/palindromic-substrings/', 'HIGH'),
  (171, '1D Dynamic Programming', 91, 'Decode Ways', 'Medium', '1-Digit & 2-Digit Valid Prefix DP', 'Meta, Amazon, Google', 'https://leetcode.com/problems/decode-ways/', 'HIGH'),
  (172, '1D Dynamic Programming', 322, 'Coin Change', 'Medium', 'Unbounded Knapsack Min Coins DP', 'Amazon, Microsoft, Google', 'https://leetcode.com/problems/coin-change/', 'HIGH'),
  (173, '1D Dynamic Programming', 152, 'Maximum Product Subarray', 'Medium', 'Min-Max Negative Flip Tracking', 'Amazon, Google, Microsoft', 'https://leetcode.com/problems/maximum-product-subarray/', 'HIGH'),
  (174, '1D Dynamic Programming', 139, 'Word Break', 'Medium', 'Trie/Set Substring Validity DP', 'Amazon, Meta, Google', 'https://leetcode.com/problems/word-break/', 'HIGH'),
  (175, '1D Dynamic Programming', 300, 'Longest Increasing Subsequence', 'Medium', 'Binary Search Patience Sorting O(n log n)', 'Amazon, Google, Microsoft', 'https://leetcode.com/problems/longest-increasing-subsequence/', 'HIGH'),
  (176, '1D Dynamic Programming', 416, 'Partition Equal Subset Sum', 'Medium', '0/1 Knapsack Target = Sum / 2', 'Amazon, Meta, Google', 'https://leetcode.com/problems/partition-equal-subset-sum/', 'HIGH'),
  (177, '1D Dynamic Programming', 343, 'Integer Break', 'Medium', 'Greedy Factor 3 Max Product', 'Amazon, Google', 'https://leetcode.com/problems/integer-break/', 'HIGH'),
  (178, '1D Dynamic Programming', 279, 'Perfect Squares', 'Medium', 'Lagrange 4-Square Theorem / 1D DP', 'Google, Amazon', 'https://leetcode.com/problems/perfect-squares/', 'HIGH'),
  (179, '2D / Grid & String DP', 62, 'Unique Paths', 'Medium', '2D Grid Transition DP[r][c]', 'Amazon, Google, Meta', 'https://leetcode.com/problems/unique-paths/', 'HIGH'),
  (180, '2D / Grid & String DP', 63, 'Unique Paths II', 'Medium', 'Grid DP with Obstacle Zeroing', 'Amazon, Google', 'https://leetcode.com/problems/unique-paths-ii/', 'HIGH'),
  (181, '2D / Grid & String DP', 64, 'Minimum Path Sum', 'Medium', 'Top & Left Minimum Influx DP', 'Amazon, Google', 'https://leetcode.com/problems/minimum-path-sum/', 'HIGH'),
  (182, '2D / Grid & String DP', 1143, 'Longest Common Subsequence', 'Medium', '2D Character Match Grid DP', 'Amazon, Meta, Google', 'https://leetcode.com/problems/longest-common-subsequence/', 'HIGH'),
  (183, '2D / Grid & String DP', 309, 'Best Time to Buy and Sell Stock with Cooldown', 'Medium', 'State Machine DP (Buy, Sell, Rest)', 'Amazon, Google', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', 'HIGH'),
  (184, '2D / Grid & String DP', 518, 'Coin Change II', 'Medium', 'Unbounded Knapsack Ways DP', 'Amazon, Google', 'https://leetcode.com/problems/coin-change-ii/', 'HIGH'),
  (185, '2D / Grid & String DP', 494, 'Target Sum', 'Medium', 'Subset Sum Transformation DP', 'Meta, Amazon, Google', 'https://leetcode.com/problems/target-sum/', 'HIGH'),
  (186, '2D / Grid & String DP', 97, 'Interleaving String', 'Medium', '2D String Pointers Interleave DP', 'Amazon, Google', 'https://leetcode.com/problems/interleaving-string/', 'HIGH'),
  (187, '2D / Grid & String DP', 72, 'Edit Distance', 'Hard', 'Levenshtein Distance 2D Table', 'Google, Amazon, Meta', 'https://leetcode.com/problems/edit-distance/', 'HIGH'),
  (188, '2D / Grid & String DP', 115, 'Distinct Subsequences', 'Hard', '2D Subsequence Multiplicity DP', 'Amazon, Google', 'https://leetcode.com/problems/distinct-subsequences/', 'HIGH'),
  (189, '2D / Grid & String DP', 10, 'Regular Expression Matching', 'Hard', '2D Star and Dot Transition DP', 'Meta, Google, Amazon', 'https://leetcode.com/problems/regular-expression-matching/', 'HIGH'),
  (190, '2D / Grid & String DP', 44, 'Wildcard Matching', 'Hard', '2D Star Wildcard Matrix DP', 'Amazon, Google', 'https://leetcode.com/problems/wildcard-matching/', 'HIGH'),
  (191, '2D / Grid & String DP', 221, 'Maximal Square', 'Medium', 'Min(Top, Left, Diagonal) + 1 DP', 'Amazon, Apple, Google', 'https://leetcode.com/problems/maximal-square/', 'HIGH'),
  (192, '2D / Grid & String DP', 329, 'Longest Increasing Path in a Matrix', 'Hard', 'DFS + Memoization DAG', 'Google, Amazon', 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/', 'HIGH'),
  (193, 'Knapsack, Subsequence & Interval DP', 474, 'Ones and Zeroes', 'Medium', '2D Capacity 0/1 Knapsack DP', 'Google, Amazon', 'https://leetcode.com/problems/ones-and-zeroes/', 'HIGH'),
  (194, 'Knapsack, Subsequence & Interval DP', 1049, 'Last Stone Weight II', 'Medium', 'Partition Sum Difference Knapsack', 'Amazon, Google', 'https://leetcode.com/problems/last-stone-weight-ii/', 'HIGH'),
  (195, 'Knapsack, Subsequence & Interval DP', 312, 'Burst Balloons', 'Hard', 'Interval DP [left, right] Last Burst Coin', 'Amazon, Google', 'https://leetcode.com/problems/burst-balloons/', 'HIGH'),
  (196, 'Knapsack, Subsequence & Interval DP', 1547, 'Minimum Cost to Cut a Stick', 'Hard', 'Interval DP on Sorted Cuts', 'Google, Amazon', 'https://leetcode.com/problems/minimum-cost-to-cut-a-stick/', 'HIGH'),
  (197, 'Knapsack, Subsequence & Interval DP', 664, 'Strange Printer', 'Hard', 'Interval DP Character Match Skipping', 'Google', 'https://leetcode.com/problems/strange-printer/', 'HIGH'),
  (198, 'Knapsack, Subsequence & Interval DP', 516, 'Longest Palindromic Subsequence', 'Medium', 'Interval DP S[i] == S[j]', 'Amazon, Meta', 'https://leetcode.com/problems/longest-palindromic-subsequence/', 'HIGH'),
  (199, 'Knapsack, Subsequence & Interval DP', 877, 'Stone Game', 'Medium', 'Minimax Game DP / Parity Proof', 'Google', 'https://leetcode.com/problems/stone-game/', 'HIGH'),
  (200, 'Knapsack, Subsequence & Interval DP', 1140, 'Stone Game II', 'Medium', 'Game Theory DP with M-Multiplier', 'Google, Amazon', 'https://leetcode.com/problems/stone-game-ii/', 'HIGH'),
  (201, 'Greedy & Intervals', 53, 'Maximum Subarray', 'Easy', 'Kadane''s Algorithm', 'Amazon, Microsoft, Apple, Google', 'https://leetcode.com/problems/maximum-subarray/', 'HIGH'),
  (202, 'Greedy & Intervals', 55, 'Jump Game', 'Medium', 'Max Reachable Index Greedy Forward', 'Amazon, Meta, Google', 'https://leetcode.com/problems/jump-game/', 'HIGH'),
  (203, 'Greedy & Intervals', 45, 'Jump Game II', 'Medium', 'BFS-Level Greedy Window Range', 'Amazon, Google', 'https://leetcode.com/problems/jump-game-ii/', 'HIGH'),
  (204, 'Greedy & Intervals', 134, 'Gas Station', 'Medium', 'Total Surplus & Deficit Reset Index', 'Amazon, Microsoft', 'https://leetcode.com/problems/gas-station/', 'HIGH'),
  (205, 'Greedy & Intervals', 846, 'Hand of Straights', 'Medium', 'Min-Heap / TreeMap Consecutive Frequency', 'Google, Amazon', 'https://leetcode.com/problems/hand-of-straights/', 'HIGH'),
  (206, 'Greedy & Intervals', 56, 'Merge Intervals', 'Medium', 'Sort by Start Time & Extend End', 'Amazon, Google, Meta, Microsoft', 'https://leetcode.com/problems/merge-intervals/', 'HIGH'),
  (207, 'Greedy & Intervals', 57, 'Insert Interval', 'Medium', 'Before, Overlapping Merge, After', 'Google, Meta, Amazon', 'https://leetcode.com/problems/insert-interval/', 'HIGH'),
  (208, 'Greedy & Intervals', 435, 'Non-overlapping Intervals', 'Medium', 'Greedy Earliest End Time Selection', 'Amazon, Meta', 'https://leetcode.com/problems/non-overlapping-intervals/', 'HIGH'),
  (209, 'Greedy & Intervals', 252, 'Meeting Rooms', 'Easy', 'Adjacent Start/End Overlap Check', 'Amazon, Meta, Google', 'https://leetcode.com/problems/meeting-rooms/', 'HIGH'),
  (210, 'Greedy & Intervals', 253, 'Meeting Rooms II', 'Medium', 'Two Pointers Start/End Sort / Min-Heap', 'Amazon, Google, Meta, Bloomberg', 'https://leetcode.com/problems/meeting-rooms-ii/', 'HIGH'),
  (211, 'Greedy & Intervals', 452, 'Minimum Number of Arrows to Burst Balloons', 'Medium', 'Sort by End Point Greedy Intersection', 'Meta, Google', 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/', 'HIGH'),
  (212, 'Greedy & Intervals', 763, 'Partition Labels', 'Medium', 'Last Occurrence Map Greedy Expansion', 'Amazon, Google', 'https://leetcode.com/problems/partition-labels/', 'HIGH'),
  (213, 'Bit Manipulation', 136, 'Single Number', 'Easy', 'XOR Cumulative Identity', 'Amazon, Google, Meta', 'https://leetcode.com/problems/single-number/', 'MEDIUM'),
  (214, 'Bit Manipulation', 191, 'Number of 1 Bits', 'Easy', 'Brian Kernighan''s (n & (n - 1))', 'Apple, Microsoft, Amazon', 'https://leetcode.com/problems/number-of-1-bits/', 'MEDIUM'),
  (215, 'Bit Manipulation', 338, 'Counting Bits', 'Easy', 'DP Bit Count (dp[i] = dp[i >> 1] + (i & 1))', 'Amazon, Meta', 'https://leetcode.com/problems/counting-bits/', 'MEDIUM'),
  (216, 'Bit Manipulation', 190, 'Reverse Bits', 'Easy', 'Bit Shifting 32-Bit Reversal', 'Apple, Amazon', 'https://leetcode.com/problems/reverse-bits/', 'MEDIUM'),
  (217, 'Bit Manipulation', 268, 'Missing Number', 'Easy', 'XOR Indices with Values / Gauss Sum', 'Amazon, Microsoft', 'https://leetcode.com/problems/missing-number/', 'MEDIUM'),
  (218, 'Bit Manipulation', 371, 'Sum of Two Integers', 'Medium', 'XOR Sum & AND Carry Shift', 'Meta, Google', 'https://leetcode.com/problems/sum-of-two-integers/', 'MEDIUM'),
  (219, 'Bit Manipulation', 7, 'Reverse Integer', 'Medium', 'Modulo Digit Accumulation with 32-bit Overflow Check', 'Amazon, Google', 'https://leetcode.com/problems/reverse-integer/', 'MEDIUM'),
  (220, 'Bit Manipulation', 137, 'Single Number II', 'Medium', 'Bit Counting Modulo 3 / Ones and Twos', 'Google, Amazon', 'https://leetcode.com/problems/single-number-ii/', 'MEDIUM'),
  (221, 'Bit Manipulation', 260, 'Single Number III', 'Medium', 'Differentiating Rightmost Set Bit', 'Amazon, Google', 'https://leetcode.com/problems/single-number-iii/', 'MEDIUM'),
  (222, 'Bit Manipulation', 201, 'Bitwise AND of Numbers Range', 'Medium', 'Common Bit Prefix Shift', 'Google', 'https://leetcode.com/problems/bitwise-and-of-numbers-range/', 'MEDIUM'),
  (223, 'Math & Number Theory', 202, 'Happy Number', 'Easy', 'Floyd Cycle on Digit Squares', 'Google, Amazon', 'https://leetcode.com/problems/happy-number/', 'MEDIUM'),
  (224, 'Math & Number Theory', 66, 'Plus One', 'Easy', 'Right-to-Left Carry Propagation', 'Google, Amazon', 'https://leetcode.com/problems/plus-one/', 'MEDIUM'),
  (225, 'Math & Number Theory', 50, 'Pow(x, n)', 'Medium', 'Binary Exponentiation O(log n)', 'Meta, Google, Amazon', 'https://leetcode.com/problems/powx-n/', 'MEDIUM'),
  (226, 'Math & Number Theory', 43, 'Multiply Strings', 'Medium', 'Position by Position Arithmetic', 'Meta, Google', 'https://leetcode.com/problems/multiply-strings/', 'MEDIUM'),
  (227, 'Math & Number Theory', 2013, 'Detect Squares', 'Medium', 'Diagonal Coordinate Hash Counting', 'Google', 'https://leetcode.com/problems/detect-squares/', 'MEDIUM'),
  (228, 'Math & Number Theory', 166, 'Fraction to Recurring Decimal', 'Medium', 'Remainder Map for Cycle Detection', 'Google, Meta', 'https://leetcode.com/problems/fraction-to-recurring-decimal/', 'MEDIUM'),
  (229, 'Math & Number Theory', 172, 'Factorial Trailing Zeroes', 'Medium', 'Count Factors of 5 (n/5 + n/25 + ...)', 'Microsoft, Amazon', 'https://leetcode.com/problems/factorial-trailing-zeroes/', 'MEDIUM'),
  (230, 'Math & Number Theory', 149, 'Max Points on a Line', 'Hard', 'Slope GCD Hash Map with Precision Avoidance', 'Google, Amazon', 'https://leetcode.com/problems/max-points-on-a-line/', 'HIGH'),
  (231, 'Math & Number Theory', 69, 'Sqrt(x)', 'Easy', 'Binary Search / Newton-Raphson', 'Apple, Bloomberg', 'https://leetcode.com/problems/sqrtx/', 'MEDIUM'),
  (232, 'Math & Number Theory', 593, 'Valid Square', 'Medium', '4 Equal Sides & 2 Equal Diagonals', 'Google', 'https://leetcode.com/problems/valid-square/', 'MEDIUM'),
  (233, 'Design (LLD-style)', 460, 'LFU Cache', 'Hard', 'Doubly Linked List per Frequency + Map', 'Amazon, Google, Microsoft', 'https://leetcode.com/problems/lfu-cache/', 'HIGH'),
  (234, 'Design (LLD-style)', 362, 'Design Hit Counter', 'Medium', 'Circular Buffer (300 buckets) / Queue', 'Amazon, Google', 'https://leetcode.com/problems/design-hit-counter/', 'HIGH'),
  (235, 'Design (LLD-style)', 1396, 'Design Underground System', 'Medium', 'Check-in Map + Route Average Aggregator', 'Bloomberg, Amazon', 'https://leetcode.com/problems/design-underground-system/', 'HIGH'),
  (236, 'Design (LLD-style)', 588, 'Design In-Memory File System', 'Hard', 'Trie-like Tree of Directories and Files', 'Amazon, Google', 'https://leetcode.com/problems/design-in-memory-file-system/', 'HIGH'),
  (237, 'Design (LLD-style)', 353, 'Design Snake Game', 'Medium', 'Deque Body Coords + Hash Set Lookup', 'Google, Amazon', 'https://leetcode.com/problems/design-snake-game/', 'HIGH'),
  (238, 'Design (LLD-style)', 1244, 'Design Leaderboard', 'Medium', 'HashMap Scores + TreeMap / Bucket Sort', 'Bloomberg, Google', 'https://leetcode.com/problems/design-leaderboard/', 'HIGH'),
  (239, 'Design (LLD-style)', 381, 'Insert Delete GetRandom O(1) - Duplicates allowed', 'Hard', 'ArrayList + Map to Set of Indices', 'Amazon, Meta', 'https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed/', 'HIGH'),
  (240, 'Design (LLD-style)', 251, 'Flatten 2D Vector', 'Medium', 'Row & Column Iterator Pointers', 'Airbnb, Google', 'https://leetcode.com/problems/flatten-2d-vector/', 'HIGH'),
  (241, 'Prefix Sum & Matrix', 303, 'Range Sum Query - Immutable', 'Easy', '1D Prefix Running Sum', 'Amazon, Google', 'https://leetcode.com/problems/range-sum-query-immutable/', 'MEDIUM'),
  (242, 'Prefix Sum & Matrix', 304, 'Range Sum Query 2D - Immutable', 'Medium', '2D Inclusion-Exclusion Prefix Sum', 'Meta, Google', 'https://leetcode.com/problems/range-sum-query-2d-immutable/', 'MEDIUM'),
  (243, 'Prefix Sum & Matrix', 523, 'Continuous Subarray Sum', 'Medium', 'Prefix Sum Modulo K with First Seen Map', 'Meta, Amazon', 'https://leetcode.com/problems/continuous-subarray-sum/', 'MEDIUM'),
  (244, 'Prefix Sum & Matrix', 974, 'Subarray Sums Divisible by K', 'Medium', 'Remainder Frequency Combinations', 'Amazon, Microsoft', 'https://leetcode.com/problems/subarray-sums-divisible-by-k/', 'MEDIUM'),
  (245, 'Prefix Sum & Matrix', 724, 'Find Pivot Index', 'Easy', 'Total Sum - Left Sum Equality Check', 'Amazon, Google', 'https://leetcode.com/problems/find-pivot-index/', 'MEDIUM'),
  (246, 'Strings & Pattern Matching', 14, 'Longest Common Prefix', 'Easy', 'Horizontal / Vertical Character Scan', 'Amazon, Google, Apple', 'https://leetcode.com/problems/longest-common-prefix/', 'MEDIUM'),
  (247, 'Strings & Pattern Matching', 8, 'String to Integer (atoi)', 'Medium', 'Whitespace, Sign, 32-bit Clamping Logic', 'Amazon, Microsoft, Meta', 'https://leetcode.com/problems/string-to-integer-atoi/', 'MEDIUM'),
  (248, 'Strings & Pattern Matching', 28, 'Find the Index of the First Occurrence in a String', 'Easy', 'KMP / Rabin-Karp / Rolling Hash', 'Amazon, Google', 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/', 'MEDIUM'),
  (249, 'Strings & Pattern Matching', 187, 'Repeated DNA Sequences', 'Medium', '10-Letter Bitmask Hash Rolling Window', 'Amazon, Google', 'https://leetcode.com/problems/repeated-dna-sequences/', 'MEDIUM'),
  (250, 'Strings & Pattern Matching', 336, 'Palindrome Pairs', 'Hard', 'Trie / Reverse String Prefix-Suffix Palindrome Check', 'Google, Airbnb', 'https://leetcode.com/problems/palindrome-pairs/', 'HIGH')
ON CONFLICT (lc_number, problem_name) DO UPDATE SET
  category_name = EXCLUDED.category_name,
  difficulty = EXCLUDED.difficulty,
  pattern = EXCLUDED.pattern,
  companies = EXCLUDED.companies,
  leetcode_url = EXCLUDED.leetcode_url,
  priority = EXCLUDED.priority;

-- 4. DSA ALREADY SOLVED REVISION SET (154 Curated Problems)
INSERT INTO dsa_already_solved (category_name, lc_number, problem_name, difficulty, leetcode_url) VALUES
  ('Arrays & Hashing', 1, 'Two Sum', 'Easy', 'https://leetcode.com/problems/two-sum/'),
  ('Arrays & Hashing', 217, 'Contains Duplicate', 'Easy', 'https://leetcode.com/problems/contains-duplicate/'),
  ('Arrays & Hashing', 242, 'Valid Anagram', 'Easy', 'https://leetcode.com/problems/valid-anagram/'),
  ('Arrays & Hashing', 49, 'Group Anagrams', 'Medium', 'https://leetcode.com/problems/group-anagrams/'),
  ('Arrays & Hashing', 347, 'Top K Frequent Elements', 'Medium', 'https://leetcode.com/problems/top-k-frequent-elements/'),
  ('Arrays & Hashing', 238, 'Product of Array Except Self', 'Medium', 'https://leetcode.com/problems/product-of-array-except-self/'),
  ('Arrays & Hashing', 36, 'Valid Sudoku', 'Medium', 'https://leetcode.com/problems/valid-sudoku/'),
  ('Arrays & Hashing', 128, 'Longest Consecutive Sequence', 'Medium', 'https://leetcode.com/problems/longest-consecutive-sequence/'),
  ('Arrays & Hashing', 271, 'Encode and Decode Strings', 'Medium', 'https://leetcode.com/problems/encode-and-decode-strings/'),
  ('Arrays & Hashing', 75, 'Sort Colors', 'Medium', 'https://leetcode.com/problems/sort-colors/'),
  ('Arrays & Hashing', 169, 'Majority Element', 'Easy', 'https://leetcode.com/problems/majority-element/'),
  ('Arrays & Hashing', 229, 'Majority Element II', 'Medium', 'https://leetcode.com/problems/majority-element-ii/'),
  ('Arrays & Hashing', 448, 'Find All Numbers Disappeared in an Array', 'Easy', 'https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/'),
  ('Arrays & Hashing', 560, 'Subarray Sum Equals K', 'Medium', 'https://leetcode.com/problems/subarray-sum-equals-k/'),
  ('Arrays & Hashing', 380, 'Insert Delete GetRandom O(1)', 'Medium', 'https://leetcode.com/problems/insert-delete-getrandom-o1/'),
  ('Arrays & Hashing', 31, 'Next Permutation', 'Medium', 'https://leetcode.com/problems/next-permutation/'),
  ('Arrays & Hashing', 54, 'Spiral Matrix', 'Medium', 'https://leetcode.com/problems/spiral-matrix/'),
  ('Arrays & Hashing', 48, 'Rotate Image', 'Medium', 'https://leetcode.com/problems/rotate-image/'),
  ('Arrays & Hashing', 73, 'Set Matrix Zeroes', 'Medium', 'https://leetcode.com/problems/set-matrix-zeroes/'),
  ('Arrays & Hashing', 41, 'First Missing Positive', 'Hard', 'https://leetcode.com/problems/first-missing-positive/'),
  ('Two Pointers', 125, 'Valid Palindrome', 'Easy', 'https://leetcode.com/problems/valid-palindrome/'),
  ('Two Pointers', 167, 'Two Sum II - Input Array Is Sorted', 'Medium', 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/'),
  ('Two Pointers', 15, '3Sum', 'Medium', 'https://leetcode.com/problems/3sum/'),
  ('Two Pointers', 16, '3Sum Closest', 'Medium', 'https://leetcode.com/problems/3sum-closest/'),
  ('Two Pointers', 18, '4Sum', 'Medium', 'https://leetcode.com/problems/4sum/'),
  ('Two Pointers', 11, 'Container With Most Water', 'Medium', 'https://leetcode.com/problems/container-with-most-water/'),
  ('Two Pointers', 42, 'Trapping Rain Water', 'Hard', 'https://leetcode.com/problems/trapping-rain-water/'),
  ('Two Pointers', 283, 'Move Zeroes', 'Easy', 'https://leetcode.com/problems/move-zeroes/'),
  ('Two Pointers', 26, 'Remove Duplicates from Sorted Array', 'Easy', 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/'),
  ('Two Pointers', 977, 'Squares of a Sorted Array', 'Easy', 'https://leetcode.com/problems/squares-of-a-sorted-array/'),
  ('Sliding Window', 121, 'Best Time to Buy and Sell Stock', 'Easy', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/'),
  ('Sliding Window', 3, 'Longest Substring Without Repeating Characters', 'Medium', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/'),
  ('Sliding Window', 424, 'Longest Repeating Character Replacement', 'Medium', 'https://leetcode.com/problems/longest-repeating-character-replacement/'),
  ('Sliding Window', 567, 'Permutation in String', 'Medium', 'https://leetcode.com/problems/permutation-in-string/'),
  ('Sliding Window', 76, 'Minimum Window Substring', 'Hard', 'https://leetcode.com/problems/minimum-window-substring/'),
  ('Sliding Window', 239, 'Sliding Window Maximum', 'Hard', 'https://leetcode.com/problems/sliding-window-maximum/'),
  ('Sliding Window', 209, 'Minimum Size Subarray Sum', 'Medium', 'https://leetcode.com/problems/minimum-size-subarray-sum/'),
  ('Sliding Window', 904, 'Fruit Into Baskets', 'Medium', 'https://leetcode.com/problems/fruit-into-baskets/'),
  ('Sliding Window', 1004, 'Max Consecutive Ones III', 'Medium', 'https://leetcode.com/problems/max-consecutive-ones-iii/'),
  ('Sliding Window', 438, 'Find All Anagrams in a String', 'Medium', 'https://leetcode.com/problems/find-all-anagrams-in-a-string/'),
  ('Stack & Monotonic Stack', 20, 'Valid Parentheses', 'Easy', 'https://leetcode.com/problems/valid-parentheses/'),
  ('Stack & Monotonic Stack', 155, 'Min Stack', 'Medium', 'https://leetcode.com/problems/min-stack/'),
  ('Stack & Monotonic Stack', 150, 'Evaluate Reverse Polish Notation', 'Medium', 'https://leetcode.com/problems/evaluate-reverse-polish-notation/'),
  ('Stack & Monotonic Stack', 22, 'Generate Parentheses', 'Medium', 'https://leetcode.com/problems/generate-parentheses/'),
  ('Stack & Monotonic Stack', 739, 'Daily Temperatures', 'Medium', 'https://leetcode.com/problems/daily-temperatures/'),
  ('Stack & Monotonic Stack', 853, 'Car Fleet', 'Medium', 'https://leetcode.com/problems/car-fleet/'),
  ('Stack & Monotonic Stack', 84, 'Largest Rectangle in Histogram', 'Hard', 'https://leetcode.com/problems/largest-rectangle-in-histogram/'),
  ('Stack & Monotonic Stack', 85, 'Maximal Rectangle', 'Hard', 'https://leetcode.com/problems/maximal-rectangle/'),
  ('Stack & Monotonic Stack', 901, 'Online Stock Span', 'Medium', 'https://leetcode.com/problems/online-stock-span/'),
  ('Stack & Monotonic Stack', 735, 'Asteroid Collision', 'Medium', 'https://leetcode.com/problems/asteroid-collision/'),
  ('Stack & Monotonic Stack', 496, 'Next Greater Element I', 'Easy', 'https://leetcode.com/problems/next-greater-element-i/'),
  ('Binary Search', 704, 'Binary Search', 'Easy', 'https://leetcode.com/problems/binary-search/'),
  ('Binary Search', 74, 'Search a 2D Matrix', 'Medium', 'https://leetcode.com/problems/search-a-2d-matrix/'),
  ('Binary Search', 875, 'Koko Eating Bananas', 'Medium', 'https://leetcode.com/problems/koko-eating-bananas/'),
  ('Binary Search', 153, 'Find Minimum in Rotated Sorted Array', 'Medium', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/'),
  ('Binary Search', 33, 'Search in Rotated Sorted Array', 'Medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array/'),
  ('Binary Search', 981, 'Time Based Key-Value Store', 'Medium', 'https://leetcode.com/problems/time-based-key-value-store/'),
  ('Binary Search', 4, 'Median of Two Sorted Arrays', 'Hard', 'https://leetcode.com/problems/median-of-two-sorted-arrays/'),
  ('Binary Search', 162, 'Find Peak Element', 'Medium', 'https://leetcode.com/problems/find-peak-element/'),
  ('Binary Search', 1011, 'Capacity To Ship Packages Within D Days', 'Medium', 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/'),
  ('Binary Search', 34, 'Find First and Last Position of Element in Sorted Array', 'Medium', 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/'),
  ('Linked List', 206, 'Reverse Linked List', 'Easy', 'https://leetcode.com/problems/reverse-linked-list/'),
  ('Linked List', 21, 'Merge Two Sorted Lists', 'Easy', 'https://leetcode.com/problems/merge-two-sorted-lists/'),
  ('Linked List', 143, 'Reorder List', 'Medium', 'https://leetcode.com/problems/reorder-list/'),
  ('Linked List', 19, 'Remove Nth Node From End of List', 'Medium', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/'),
  ('Linked List', 138, 'Copy List with Random Pointer', 'Medium', 'https://leetcode.com/problems/copy-list-with-random-pointer/'),
  ('Linked List', 2, 'Add Two Numbers', 'Medium', 'https://leetcode.com/problems/add-two-numbers/'),
  ('Linked List', 141, 'Linked List Cycle', 'Easy', 'https://leetcode.com/problems/linked-list-cycle/'),
  ('Linked List', 287, 'Find the Duplicate Number', 'Medium', 'https://leetcode.com/problems/find-duplicate-number/'),
  ('Linked List', 146, 'LRU Cache', 'Medium', 'https://leetcode.com/problems/lru-cache/'),
  ('Linked List', 23, 'Merge k Sorted Lists', 'Hard', 'https://leetcode.com/problems/merge-k-sorted-lists/'),
  ('Linked List', 25, 'Reverse Nodes in k-Group', 'Hard', 'https://leetcode.com/problems/reverse-nodes-in-k-group/'),
  ('Binary Trees', 226, 'Invert Binary Tree', 'Easy', 'https://leetcode.com/problems/invert-binary-tree/'),
  ('Binary Trees', 104, 'Maximum Depth of Binary Tree', 'Easy', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/'),
  ('Binary Trees', 543, 'Diameter of Binary Tree', 'Easy', 'https://leetcode.com/problems/diameter-of-binary-tree/'),
  ('Binary Trees', 110, 'Balanced Binary Tree', 'Easy', 'https://leetcode.com/problems/balanced-binary-tree/'),
  ('Binary Trees', 100, 'Same Tree', 'Easy', 'https://leetcode.com/problems/same-tree/'),
  ('Binary Trees', 572, 'Subtree of Another Tree', 'Easy', 'https://leetcode.com/problems/subtree-of-another-tree/'),
  ('Binary Trees', 236, 'Lowest Common Ancestor of a Binary Tree', 'Medium', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/'),
  ('Binary Trees', 102, 'Binary Tree Level Order Traversal', 'Medium', 'https://leetcode.com/problems/binary-tree-level-order-traversal/'),
  ('Binary Trees', 199, 'Binary Tree Right Side View', 'Medium', 'https://leetcode.com/problems/binary-tree-right-side-view/'),
  ('Binary Trees', 1448, 'Count Good Nodes in Binary Tree', 'Medium', 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/'),
  ('Binary Trees', 105, 'Construct Binary Tree from Preorder and Inorder Traversal', 'Medium', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/'),
  ('Binary Trees', 124, 'Binary Tree Maximum Path Sum', 'Hard', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/'),
  ('Binary Trees', 297, 'Serialize and Deserialize Binary Tree', 'Hard', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/'),
  ('Binary Search Trees', 98, 'Validate Binary Search Tree', 'Medium', 'https://leetcode.com/problems/validate-binary-search-tree/'),
  ('Binary Search Trees', 230, 'Kth Smallest Element in a BST', 'Medium', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/'),
  ('Binary Search Trees', 235, 'Lowest Common Ancestor of a Binary Search Tree', 'Medium', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/'),
  ('Binary Search Trees', 701, 'Insert into a Binary Search Tree', 'Medium', 'https://leetcode.com/problems/insert-into-a-binary-search-tree/'),
  ('Binary Search Trees', 450, 'Delete Node in a BST', 'Medium', 'https://leetcode.com/problems/delete-node-in-a-bst/'),
  ('Heap / Priority Queue', 703, 'Kth Largest Element in a Stream', 'Easy', 'https://leetcode.com/problems/kth-largest-element-in-a-stream/'),
  ('Heap / Priority Queue', 1046, 'Last Stone Weight', 'Easy', 'https://leetcode.com/problems/last-stone-weight/'),
  ('Heap / Priority Queue', 973, 'K Closest Points to Origin', 'Medium', 'https://leetcode.com/problems/k-closest-points-to-origin/'),
  ('Heap / Priority Queue', 215, 'Kth Largest Element in an Array', 'Medium', 'https://leetcode.com/problems/kth-largest-element-in-an-array/'),
  ('Heap / Priority Queue', 621, 'Task Scheduler', 'Medium', 'https://leetcode.com/problems/task-scheduler/'),
  ('Heap / Priority Queue', 355, 'Design Twitter', 'Medium', 'https://leetcode.com/problems/design-twitter/'),
  ('Heap / Priority Queue', 295, 'Find Median from Data Stream', 'Hard', 'https://leetcode.com/problems/find-median-from-data-stream/'),
  ('Heap / Priority Queue', 767, 'Reorganize String', 'Medium', 'https://leetcode.com/problems/reorganize-string/'),
  ('Trie', 208, 'Implement Trie (Prefix Tree)', 'Medium', 'https://leetcode.com/problems/implement-trie-prefix-tree/'),
  ('Trie', 211, 'Design Add and Search Words Data Structure', 'Medium', 'https://leetcode.com/problems/design-add-and-search-words-data-structure/'),
  ('Trie', 212, 'Word Search II', 'Hard', 'https://leetcode.com/problems/word-search-ii/'),
  ('Backtracking', 78, 'Subsets', 'Medium', 'https://leetcode.com/problems/subsets/'),
  ('Backtracking', 90, 'Subsets II', 'Medium', 'https://leetcode.com/problems/subsets-ii/'),
  ('Backtracking', 39, 'Combination Sum', 'Medium', 'https://leetcode.com/problems/combination-sum/'),
  ('Backtracking', 40, 'Combination Sum II', 'Medium', 'https://leetcode.com/problems/combination-sum-ii/'),
  ('Backtracking', 46, 'Permutations', 'Medium', 'https://leetcode.com/problems/permutations/'),
  ('Backtracking', 79, 'Word Search', 'Medium', 'https://leetcode.com/problems/word-search/'),
  ('Backtracking', 131, 'Palindrome Partitioning', 'Medium', 'https://leetcode.com/problems/palindrome-partitioning/'),
  ('Backtracking', 17, 'Letter Combinations of a Phone Number', 'Medium', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/'),
  ('Backtracking', 51, 'N-Queens', 'Hard', 'https://leetcode.com/problems/n-queens/'),
  ('Graphs: BFS & DFS', 200, 'Number of Islands', 'Medium', 'https://leetcode.com/problems/number-of-islands/'),
  ('Graphs: BFS & DFS', 695, 'Max Area of Island', 'Medium', 'https://leetcode.com/problems/max-area-of-island/'),
  ('Graphs: BFS & DFS', 133, 'Clone Graph', 'Medium', 'https://leetcode.com/problems/clone-graph/'),
  ('Graphs: BFS & DFS', 417, 'Pacific Atlantic Water Flow', 'Medium', 'https://leetcode.com/problems/pacific-atlantic-water-flow/'),
  ('Graphs: BFS & DFS', 130, 'Surrounded Regions', 'Medium', 'https://leetcode.com/problems/surrounded-regions/'),
  ('Graphs: BFS & DFS', 994, 'Rotting Oranges', 'Medium', 'https://leetcode.com/problems/rotting-oranges/'),
  ('Graphs: BFS & DFS', 286, 'Walls and Gates', 'Medium', 'https://leetcode.com/problems/walls-and-gates/'),
  ('Graphs: BFS & DFS', 127, 'Word Ladder', 'Hard', 'https://leetcode.com/problems/word-ladder/'),
  ('Graphs: BFS & DFS', 207, 'Course Schedule', 'Medium', 'https://leetcode.com/problems/course-schedule/'),
  ('Graphs: BFS & DFS', 210, 'Course Schedule II', 'Medium', 'https://leetcode.com/problems/course-schedule-ii/'),
  ('Graphs: Topological Sort, Union-Find, Shortest Path', 743, 'Network Delay Time', 'Medium', 'https://leetcode.com/problems/network-delay-time/'),
  ('Graphs: Topological Sort, Union-Find, Shortest Path', 787, 'Cheapest Flights Within K Stops', 'Medium', 'https://leetcode.com/problems/cheapest-flights-within-k-stops/'),
  ('Graphs: Topological Sort, Union-Find, Shortest Path', 1584, 'Min Cost to Connect All Points', 'Medium', 'https://leetcode.com/problems/min-cost-to-connect-all-points/'),
  ('Graphs: Topological Sort, Union-Find, Shortest Path', 684, 'Redundant Connection', 'Medium', 'https://leetcode.com/problems/redundant-connection/'),
  ('1D Dynamic Programming', 70, 'Climbing Stairs', 'Easy', 'https://leetcode.com/problems/climbing-stairs/'),
  ('1D Dynamic Programming', 746, 'Min Cost Climbing Stairs', 'Easy', 'https://leetcode.com/problems/min-cost-climbing-stairs/'),
  ('1D Dynamic Programming', 198, 'House Robber', 'Medium', 'https://leetcode.com/problems/house-robber/'),
  ('1D Dynamic Programming', 213, 'House Robber II', 'Medium', 'https://leetcode.com/problems/house-robber-ii/'),
  ('1D Dynamic Programming', 5, 'Longest Palindromic Substring', 'Medium', 'https://leetcode.com/problems/longest-palindromic-substring/'),
  ('1D Dynamic Programming', 647, 'Palindromic Substrings', 'Medium', 'https://leetcode.com/problems/palindromic-substrings/'),
  ('1D Dynamic Programming', 91, 'Decode Ways', 'Medium', 'https://leetcode.com/problems/decode-ways/'),
  ('1D Dynamic Programming', 322, 'Coin Change', 'Medium', 'https://leetcode.com/problems/coin-change/'),
  ('1D Dynamic Programming', 152, 'Maximum Product Subarray', 'Medium', 'https://leetcode.com/problems/maximum-product-subarray/'),
  ('1D Dynamic Programming', 139, 'Word Break', 'Medium', 'https://leetcode.com/problems/word-break/'),
  ('1D Dynamic Programming', 300, 'Longest Increasing Subsequence', 'Medium', 'https://leetcode.com/problems/longest-increasing-subsequence/'),
  ('1D Dynamic Programming', 416, 'Partition Equal Subset Sum', 'Medium', 'https://leetcode.com/problems/partition-equal-subset-sum/'),
  ('2D / Grid & String DP', 62, 'Unique Paths', 'Medium', 'https://leetcode.com/problems/unique-paths/'),
  ('2D / Grid & String DP', 63, 'Unique Paths II', 'Medium', 'https://leetcode.com/problems/unique-paths-ii/'),
  ('2D / Grid & String DP', 1143, 'Longest Common Subsequence', 'Medium', 'https://leetcode.com/problems/longest-common-subsequence/'),
  ('2D / Grid & String DP', 309, 'Best Time to Buy and Sell Stock with Cooldown', 'Medium', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/'),
  ('2D / Grid & String DP', 518, 'Coin Change II', 'Medium', 'https://leetcode.com/problems/coin-change-ii/'),
  ('2D / Grid & String DP', 494, 'Target Sum', 'Medium', 'https://leetcode.com/problems/target-sum/'),
  ('2D / Grid & String DP', 72, 'Edit Distance', 'Hard', 'https://leetcode.com/problems/edit-distance/'),
  ('2D / Grid & String DP', 10, 'Regular Expression Matching', 'Hard', 'https://leetcode.com/problems/regular-expression-matching/'),
  ('Greedy & Intervals', 53, 'Maximum Subarray', 'Easy', 'https://leetcode.com/problems/maximum-subarray/'),
  ('Greedy & Intervals', 55, 'Jump Game', 'Medium', 'https://leetcode.com/problems/jump-game/'),
  ('Greedy & Intervals', 45, 'Jump Game II', 'Medium', 'https://leetcode.com/problems/jump-game-ii/'),
  ('Greedy & Intervals', 134, 'Gas Station', 'Medium', 'https://leetcode.com/problems/gas-station/'),
  ('Greedy & Intervals', 846, 'Hand of Straights', 'Medium', 'https://leetcode.com/problems/hand-of-straights/'),
  ('Greedy & Intervals', 56, 'Merge Intervals', 'Medium', 'https://leetcode.com/problems/merge-intervals/'),
  ('Greedy & Intervals', 57, 'Insert Interval', 'Medium', 'https://leetcode.com/problems/insert-interval/'),
  ('Greedy & Intervals', 435, 'Non-overlapping Intervals', 'Medium', 'https://leetcode.com/problems/non-overlapping-intervals/'),
  ('Bit Manipulation', 136, 'Single Number', 'Easy', 'https://leetcode.com/problems/single-number/'),
  ('Bit Manipulation', 191, 'Number of 1 Bits', 'Easy', 'https://leetcode.com/problems/number-of-1-bits/'),
  ('Bit Manipulation', 338, 'Counting Bits', 'Easy', 'https://leetcode.com/problems/counting-bits/'),
  ('Bit Manipulation', 190, 'Reverse Bits', 'Easy', 'https://leetcode.com/problems/reverse-bits/'),
  ('Bit Manipulation', 268, 'Missing Number', 'Easy', 'https://leetcode.com/problems/missing-number/'),
  ('Bit Manipulation', 371, 'Sum of Two Integers', 'Medium', 'https://leetcode.com/problems/sum-of-two-integers/'),
  ('Math & Number Theory', 202, 'Happy Number', 'Easy', 'https://leetcode.com/problems/happy-number/'),
  ('Math & Number Theory', 66, 'Plus One', 'Easy', 'https://leetcode.com/problems/plus-one/'),
  ('Math & Number Theory', 50, 'Pow(x, n)', 'Medium', 'https://leetcode.com/problems/powx-n/'),
  ('Math & Number Theory', 43, 'Multiply Strings', 'Medium', 'https://leetcode.com/problems/multiply-strings/'),
  ('Design (LLD-style)', 146, 'LRU Cache', 'Medium', 'https://leetcode.com/problems/lru-cache/'),
  ('Design (LLD-style)', 355, 'Design Twitter', 'Medium', 'https://leetcode.com/problems/design-twitter/'),
  ('Design (LLD-style)', 295, 'Find Median from Data Stream', 'Hard', 'https://leetcode.com/problems/find-median-from-data-stream/'),
  ('Prefix Sum & Matrix', 303, 'Range Sum Query - Immutable', 'Easy', 'https://leetcode.com/problems/range-sum-query-immutable/'),
  ('Prefix Sum & Matrix', 304, 'Range Sum Query 2D - Immutable', 'Medium', 'https://leetcode.com/problems/range-sum-query-2d-immutable/'),
  ('Prefix Sum & Matrix', 523, 'Continuous Subarray Sum', 'Medium', 'https://leetcode.com/problems/continuous-subarray-sum/'),
  ('Prefix Sum & Matrix', 724, 'Find Pivot Index', 'Easy', 'https://leetcode.com/problems/find-pivot-index/'),
  ('Strings & Pattern Matching', 14, 'Longest Common Prefix', 'Easy', 'https://leetcode.com/problems/longest-common-prefix/'),
  ('Strings & Pattern Matching', 8, 'String to Integer (atoi)', 'Medium', 'https://leetcode.com/problems/string-to-integer-atoi/'),
  ('Strings & Pattern Matching', 28, 'Find the Index of the First Occurrence in a String', 'Easy', 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/')
ON CONFLICT (lc_number, problem_name) DO UPDATE SET
  category_name = EXCLUDED.category_name,
  difficulty = EXCLUDED.difficulty,
  leetcode_url = EXCLUDED.leetcode_url;
